name: ci
env:
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']
  schedule:
    - cron: '0 0 * * *' # every day

jobs:
  run:
    name: run
    strategy:
      fail-fast: false
      matrix:
        include:
          - otp: 20.3
            elixir: 1.9.3
          - otp: 21.3
            elixir: 1.10.3
          - otp: 22.3
            elixir: 1.10.3
          - otp: 23.0
            elixir: 1.10.3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-elixir@v1.3.0
        with:
          otp-version: '${{matrix.otp}}'
          elixir-version: '${{matrix.elixir}}'
      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix compile
      - name: Expectation
        run: |
          echo "[default: \"checks out\", env: \"$USER\", gcp: \"bar\"]" > expected
      - name: Release
        env:
          MIX_ENV: prod
        run: mix release --overwrite
      - name: Test runtime
        run: |
          mix > output
          diff expected output
      - name: Test release
        run: |
          _build/prod/rel/hush_sample_app/bin/hush_sample_app start > output &
          sleep 10

          diff expected output
          kill %1
      - name: Test eval
        run: |
          _build/prod/rel/hush_sample_app/bin/hush_sample_app eval "HushSampleApp.start_eval()" > output
          diff expected output
