name: ci
env:
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  schedule:
    - cron: "0 0 * * *" # every day

jobs:
  run:
    name: run
    strategy:
      fail-fast: false
      matrix:
        include:
          - otp: 21.3
            elixir: 1.10.4
          - otp: 22.3
            elixir: 1.11.4
          - otp: 23.3
            elixir: 1.12.3
          - otp: 24.3
            elixir: 1.13.4
          - otp: 25.0
            elixir: 1.13.4
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: "${{matrix.otp}}"
          elixir-version: "${{matrix.elixir}}"
      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix compile
      - name: Expectation
        run: |
          echo '[
            apply: "runner1",
            aws_json: %{
              "dbname" => "db-name",
              "engine" => "mariadb",
              "host" => "addr.com",
              "password" => "db-creds2",
              "port" => "12345",
              "username" => "db-creds"
            },
            aws_key: %{"key" => "value"},
            default: "checks out",
            env: "runner",
            gcp_bar: "bar",
            gcp_foo: "bar",
            list: "runner",
            list_nested: [level2: [user: "runner"]],
            map: %{key: "runner"},
            map_string: %{"key" => "runner"},
            tuple: {"runner"}
          ]' > expected
      - name: Release
        env:
          MIX_ENV: prod
        run: mix release --overwrite
      - name: Test runtime
        run: |
          mix > output
          diff expected output
      - name: Test release
        run: |
          _build/prod/rel/hush_sample_app/bin/hush_sample_app start > output
          diff expected output
      - name: Test eval
        run: |
          _build/prod/rel/hush_sample_app/bin/hush_sample_app eval "HushSampleApp.print_config()" > output
          diff expected output
